<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Customer "Remember Me" template
 *
 * @var $block \Magento\Persistent\Block\Form\Remember
 */
?>
<div class="field choice persistent">
    <?php $rememberMeId = 'remember_me' . $block->getRandomString(10); ?>
    <input type="checkbox" name="persistent_remember_me" class="checkbox" id="<?php /* @escapeNotVerified */ echo $rememberMeId; ?>"<?php if ($block->isRememberMeChecked()): ?> checked="checked"<?php endif; ?> title="<?php /* @escapeNotVerified */ echo __('Remember Me') ?>" />
    <label for="<?php /* @escapeNotVerified */ echo $rememberMeId; ?>" class="label"><span><?php /* @escapeNotVerified */ echo __('Remember Me') ?></span></label>
</div>
